#
# Build an image for deploying the Neo web viewer REST API
#
# To build the image, from the parent directory:
#   docker build -t neo-viewer -f deployment/Dockerfile .
#
# To run the application:
#  docker run -d -p 443 neo-viewer
#

FROM docker-registry.ebrains.eu/neuralactivity/node:16-alpine as build

WORKDIR /js/react
ENV PATH /js/react/node_modules/.bin:$PATH
COPY js/react ./
COPY js/react/src/globals-dev.js ./src/globals.js
RUN npm run ci-all
RUN npm run build-lib
RUN node --max-old-space-size=4096 `which npm` run build-demo


FROM docker-registry.ebrains.eu/neuralactivity/debian:bookworm-slim

MAINTAINER Andrew Davison <andrew.davison@cnrs.fr>

ENV DEBIAN_FRONTEND noninteractive
RUN apt-get update --fix-missing; apt-get -y -q install python3-full supervisor nginx-extras git
RUN unset DEBIAN_FRONTEND

ENV BASEDIR /home/docker
ENV SITEDIR $BASEDIR/site

RUN python3 -m venv ${BASEDIR}/pyenv

COPY api/requirements.txt $BASEDIR/requirements.txt
RUN ${BASEDIR}/pyenv/bin/pip install -r $BASEDIR/requirements.txt
#RUN pip3 install axographio  # setup.py requires numpy, so have to install separately
RUN ${BASEDIR}/pyenv/bin/pip freeze

COPY api $SITEDIR/api
COPY homepage $SITEDIR/homepage
COPY --from=build /js/react/demo/build $SITEDIR/react

WORKDIR $SITEDIR/api

COPY deployment $BASEDIR/deployment
RUN echo "daemon off;" >> /etc/nginx/nginx.conf
RUN rm /etc/nginx/sites-enabled/default
RUN ln -s $BASEDIR/deployment/nginx-app-dev.conf /etc/nginx/sites-enabled/
RUN ln -s $BASEDIR/deployment/supervisor-app.conf /etc/supervisor/conf.d/
RUN ln -sf /dev/stdout /var/log/nginx/access.log
RUN ln -sf /dev/stderr /var/log/nginx/error.log

EXPOSE 80 443
CMD ["supervisord", "-n", "-c", "/etc/supervisor/conf.d/supervisor-app.conf"]
